### ISSUE TITLE
Really nice didactic resource

### ISSUE THREAD

**Issue by jmp75** [kurtanr/WiXInstallerExamples#17]
Hi,

I am using this "issue" to actually just say thank you. I've skimmed through and to me this feels a more didactic and pleasant resource than the current [Wix3 tutorial](https://www.firegiant.com/wix/tutorial) for newcomers.

Well done.

**Comment by kurtanr** [comment]
Hi @jmp75, 

Thank you for your kind comments. From my experience, it is not easy to find good how-to guides on various things related to WiX, so I wanted to contribute something in this area based on my experience with WiX. While I did not cover a lot of things WiX can do, I am glad that the things I did cover people find useful.

Thank you once again.

**Comment by pushphilipp** [comment]
+1 

I have to say this is way more beginner friendly than the actual documentation which does not really explain how to do simple things. I watched so many videos of people just using some GUI version of wix but this actually explains what the Tags and Attributes do. 

Thanks!!

**Comment by Raymo111** [comment]
This was indeed extremely helpful for me, thank you! A few suggestions:
- Update the schema and tutorial 00 to v4
- Cover common MSI options like Start Menu and Desktop shortcuts, preventing installing multiple of the same MSIs.
